name: Main

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
        with:
          jvm: adoptium:1.21.0.2
          apps: sbt
      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
      - name: Cache Build Files
        uses: actions/cache@v4
        with:
          path: |
            **/target
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Check Format
        run: sbt scalafmtCheckAll scalafmtSbtCheck
      - name: Test
        run: sbt test
